Load 'i_did_mean' for unknown error test
When run in isolation, `test_doesnt_explode_on_unknown_errors` was raising `NoMethodError: undefined method `call' for IDidMean:Module` because `i_did_mean` wasn't required. Essentially, if this test was to be run first, it would fail.